"""create transactions table

Revision ID: 0a277c807c27
Revises: e5d9dde5c061
Create Date: 2024-10-23 22:14:01.971909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a277c807c27'
down_revision: Union[str, None] = 'e5d9dde5c061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_links', sa.Column('link_code', sa.String, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_links', 'link_code')
    # ### end Alembic commands ###
