"""Add a column

Revision ID: cf489df4019b
Revises: 8daecb0af7fa
Create Date: 2024-10-24 01:21:13.080546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf489df4019b'
down_revision: Union[str, None] = '8daecb0af7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_links', sa.Column('link_code', sa.String, nullable=False, server_default='default_value'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_links', 'link_code')
    # ### end Alembic commands ###
